--require("config.options")
--require("config.mappings")
--require("config.lazy")

require("config.mappings")
require("config.options")

require("plugins.autumnal")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.which-key")
require("plugins.markdown")
require("config.lsp")
