if [ $PYTHONPATH ]; then
    export PYTHONPATH=.:$PYTHONPATH
else
    export PYTHONPATH=.
fi

if [ -d ~/.bash.d ]; then
    for shfile in ~/.bash.d/*.sh; do
        if [ -x $shfile ]; then
            source $shfile
        fi
    done
fi

alias x="xdg-open"
